### Get all posts
GET http://localhost:3001/posts

### Get Post By Id
GET http://localhost:3001/post/673b8d0c7c0f57ba50d479aa

###
GET http://localhost:3001/post?sender_id=123456


###

POST http://localhost:3001/posts Content-Type: application/json

{
"title": "Hello", "sender_id": "123456", "content": "Hello World..."
}

###
PUT http://localhost:3001/post/673b8d0c7c0f57ba50d479aa Content-Type: application/json

{
"title": "Hello", "sender_id": "123456", "content": "Hello World..."
}

